swagger: "2.0"
info:
  version: 1.0.0
  title: restaurantApi
  description: Restaurant API for selling sandwiches
basePath: /api/v1
tags:
  - name: Restaurant
    description: Restaurant API for selling sandwiches

consumes:
  - application/json
produces:
  - application/json


definitions:
  SandwicheBody:
    type: array
    title: sandwiches
    items:
      type: object
      properties:
        name:
          type: string
        count:
          type: integer
  
  SandwichItem:
    type: object
    title: items
    items:
      type: object
      properties:
        name:
          type: string
        value:
          type: integer


paths:
  /restaurant/items:
    get:
      tags:
        - restaurant
      description: Registered Ingredients
      responses:
        200:
          description: Returns all ingredients registered in the API
        404:
          description: Ingredients not found
          
  /restaurant/menu:
    get:
      tags:
        - restaurant
      description: available sandwiches

      responses:
        200:
          description: Return full menu with available sandwiches
        404:
          description: Menu not found
 
  /restaurant/assemble:
    post:
      tags:
        - restaurant
      description: Create a new example
      parameters:
        - name: sandwich
          in: body
          description: an example
          required: true
          schema: 
            $ref: "#/definitions/SandwicheBody"
      responses:
        200:
          description: Returns all restaurants

  /restaurant/create:
    post:
      tags:
        - restaurant
      description: Create a new item
      parameters:
        - name: sandwich
          in: body
          description: an example
          required: true
          schema: 
            $ref: "#/definitions/SandwichItem"
      responses:
        200:
          description: Insert new items